package chkdna.view;


import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author canaran
 */
public class ConfigWindow extends javax.swing.JFrame {

    final int x;
    final int y;
    String currentPath;
    public ConfigWindow() {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        x = (screenSize.width - this.getWidth()) / 2;
        y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
        this.setVisible(true);
        currentPath = System.getProperty("user.dir");
        System.out.println(currentPath);
        reportSavePath.setText(currentPath+"/Report");
        genoTableTxt.setText(currentPath+"/data/wikigwa.csv");
        pharmTxt.setText(currentPath+"/data/druggene.csv");
        mitoTxt1.setText(currentPath+"/data/HR/chrm.txt");
        chromTxt.setText(currentPath+"/data/HR/hap_snp_mut.txt");
        this.setTitle("Configuration Window");
        this.setResizable(false);
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        fileChooser2 = new javax.swing.JFileChooser();
        fileChooser3 = new javax.swing.JFileChooser();
        fileChooser4 = new javax.swing.JFileChooser();
        fileChooser5 = new javax.swing.JFileChooser();
        fileChooser6 = new javax.swing.JFileChooser();
        mainPanel = new javax.swing.JPanel();
        confLbl = new javax.swing.JLabel();
        reportSavePath = new javax.swing.JTextField();
        reportLbl = new javax.swing.JLabel();
        browseBtn1 = new javax.swing.JButton();
        databaseLbl = new javax.swing.JLabel();
        genoLbl = new javax.swing.JLabel();
        pharmLbl = new javax.swing.JLabel();
        genoTableTxt = new javax.swing.JTextField();
        browseBtn3 = new javax.swing.JButton();
        pharmTxt = new javax.swing.JTextField();
        browseBtn4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mitoLbl = new javax.swing.JLabel();
        chromTxt = new javax.swing.JTextField();
        browseBtn5 = new javax.swing.JButton();
        chromLbl = new javax.swing.JLabel();
        mitoTxt1 = new javax.swing.JTextField();
        browseBtn6 = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(233, 233, 233));

        confLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        confLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chkdna/view/img/image.jpeg"))); // NOI18N

        reportSavePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportSavePathActionPerformed(evt);
            }
        });

        reportLbl.setText("Report Save Path:");

        browseBtn1.setText("Browse");
        browseBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtn1ActionPerformed(evt);
            }
        });

        databaseLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        databaseLbl.setText("Databases");

        genoLbl.setText("Genotype/Phenotype Table:");

        pharmLbl.setText("PharmGKB:");

        browseBtn3.setText("Browse");
        browseBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtn3ActionPerformed(evt);
            }
        });

        browseBtn4.setText("Browse");
        browseBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtn4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel1.setText("Haplogroup Tables");

        mitoLbl.setText("Mitochondrion:");

        browseBtn5.setText("Browse");
        browseBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtn5ActionPerformed(evt);
            }
        });

        chromLbl.setText("Chromosome Y:");

        browseBtn6.setText("Browse");
        browseBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtn6ActionPerformed(evt);
            }
        });

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .add(confLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 576, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(databaseLbl)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, mainPanelLayout.createSequentialGroup()
                                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(mainPanelLayout.createSequentialGroup()
                                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(genoLbl)
                                            .add(pharmLbl))
                                        .add(27, 27, 27)
                                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(genoTableTxt)
                                            .add(pharmTxt)))
                                    .add(mainPanelLayout.createSequentialGroup()
                                        .add(reportLbl)
                                        .add(46, 46, 46)
                                        .add(reportSavePath)))
                                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(mainPanelLayout.createSequentialGroup()
                                        .add(28, 28, 28)
                                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, browseBtn3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, browseBtn1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(browseBtn4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(mainPanelLayout.createSequentialGroup()
                                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(mainPanelLayout.createSequentialGroup()
                                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(chromLbl)
                                            .add(jLabel1)
                                            .add(mitoLbl))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .add(mainPanelLayout.createSequentialGroup()
                                        .add(147, 147, 147)
                                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(mitoTxt1)
                                            .add(chromTxt))
                                        .add(6, 6, 6)))
                                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(mainPanelLayout.createSequentialGroup()
                                        .add(22, 22, 22)
                                        .add(browseBtn6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, browseBtn5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, mainPanelLayout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(confirmButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .add(confLbl)
                .add(30, 30, 30)
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(reportLbl)
                    .add(reportSavePath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(browseBtn1))
                .add(31, 31, 31)
                .add(databaseLbl)
                .add(21, 21, 21)
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(genoLbl)
                    .add(genoTableTxt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(browseBtn3))
                .add(18, 18, 18)
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pharmLbl)
                    .add(pharmTxt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(browseBtn4))
                .add(38, 38, 38)
                .add(jLabel1)
                .add(28, 28, 28)
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(mitoLbl)
                    .add(mitoTxt1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(browseBtn6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(chromLbl)
                    .add(chromTxt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(browseBtn5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 39, Short.MAX_VALUE)
                .add(confirmButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, mainPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(mainPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportSavePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportSavePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportSavePathActionPerformed

    private void browseBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn1ActionPerformed
        fileChooser.setDialogTitle("Report Directory");
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            reportSavePath.setText(fileChooser.getSelectedFile().getPath().toString());
        }
    }//GEN-LAST:event_browseBtn1ActionPerformed

    private void browseBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn3ActionPerformed
        fileChooser3.setDialogTitle("Genotype Table Path");
        fileChooser3.setFileFilter(new FileNameExtensionFilter("CSV and TSV Files", "csv","tsv"));
        if(fileChooser3.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            genoTableTxt.setText(fileChooser3.getSelectedFile().getPath().toString());
        }
    }//GEN-LAST:event_browseBtn3ActionPerformed

    private void browseBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn4ActionPerformed
        fileChooser4.setDialogTitle("PharmGKB Table Path");
        fileChooser4.setFileFilter(new FileNameExtensionFilter("CSV and TSV Files", "csv","tsv"));
        if(fileChooser4.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            pharmTxt.setText(fileChooser4.getSelectedFile().getPath().toString());
        }
    }//GEN-LAST:event_browseBtn4ActionPerformed

    private void browseBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn6ActionPerformed
        fileChooser5.setDialogTitle("Mitochondiron Table Path");
        fileChooser5.setFileFilter(new FileNameExtensionFilter("CSV and TSV Files", "csv","tsv","txt"));
        if(fileChooser5.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            mitoTxt1.setText(fileChooser5.getSelectedFile().getPath().toString());
        }
    }//GEN-LAST:event_browseBtn6ActionPerformed

    private void browseBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn5ActionPerformed
        fileChooser6.setDialogTitle("Chromosome Y Table Path");
        fileChooser6.setFileFilter(new FileNameExtensionFilter("CSV and TSV Files", "csv","tsv","txt"));
        if(fileChooser6.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            chromTxt.setText(fileChooser6.getSelectedFile().getPath().toString());
        }
    }//GEN-LAST:event_browseBtn5ActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_confirmButtonActionPerformed
    {//GEN-HEADEREND:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        // All fields will be sent to the static class Config
        Config.setReportSavePath(reportSavePath.getText());
        Config.setPhenotypeTablePath(genoTableTxt.getText());
        Config.setPharmGKBPath(pharmTxt.getText());
        Config.setMitokondriPath(mitoTxt1.getText());
        Config.setChromosomeYPath(chromTxt.getText());
        this.setVisible(false);
    }//GEN-LAST:event_confirmButtonActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn1;
    private javax.swing.JButton browseBtn3;
    private javax.swing.JButton browseBtn4;
    private javax.swing.JButton browseBtn5;
    private javax.swing.JButton browseBtn6;
    private javax.swing.JLabel chromLbl;
    private javax.swing.JTextField chromTxt;
    private javax.swing.JLabel confLbl;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel databaseLbl;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JFileChooser fileChooser2;
    private javax.swing.JFileChooser fileChooser3;
    private javax.swing.JFileChooser fileChooser4;
    private javax.swing.JFileChooser fileChooser5;
    private javax.swing.JFileChooser fileChooser6;
    private javax.swing.JLabel genoLbl;
    private javax.swing.JTextField genoTableTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mitoLbl;
    private javax.swing.JTextField mitoTxt1;
    private javax.swing.JLabel pharmLbl;
    private javax.swing.JTextField pharmTxt;
    private javax.swing.JLabel reportLbl;
    private javax.swing.JTextField reportSavePath;
    // End of variables declaration//GEN-END:variables
}
